name: parallel-examples

on: 
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code
        run: echo "Linting code..."

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: echo "Running unit tests..."

  intergration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up test environment
        run: echo "Setting up test environment..."
      - name: Run integration tests
        run: echo "Running integration tests..."
